# Introduction to NumPy

NumPy is a Python library used for working with arrays.

The NumPy (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data.

In [2]:
import numpy as np

## Numpy array

**`arrays`**: The central feature of NumPy is the array object class. Arrays are similar to lists in Python, except that every element of an array must be of the same type, usually a numeric type like float or int. 

Arrays make operations with large amounts of numeric data very fast and are much efficient than lists.

In [3]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print('Type of arr  =', type(arr))
print('Type of arr2 =', type(arr2))

Type of arr  = <class 'numpy.ndarray'>
Type of arr2 = <class 'numpy.ndarray'>


Array Dimensions: number of axes

In [6]:
print('Dimensions of arr  =', arr.ndim)
print('Dimensions of arr2 =', arr2.ndim)

Dimensions of arr  = 1
Dimensions of arr2 = 2


Array Shape: number of elements in each dimension

In [7]:
print('Shape of arr  =', arr.shape)
print('Shape of arr2 =', arr2.shape)

Shape of arr  = (6,)
Shape of arr2 = (2, 3)


Array Size: total number of elements

In [8]:
print('Size of arr  =', arr.size)
print('Size of arr2 =', arr2.size)

Size of arr  = 6
Size of arr2 = 6


Type of the elements in the array

In [9]:
print('Type of elements in arr  =', arr.dtype)
print('Type of elements in arr2 =', arr2.dtype)

Type of elements in arr  = int32
Type of elements in arr2 = int32


## Array creation

There are several ways to create arrays in Numpy

In [10]:
arr_l = np.array([[1, 2, 3], [4, 5, 6]], dtype = 'float')
arr_l

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
arr_l.dtype

dtype('float64')

Creating an array from a tuple:

In [12]:
arr_t = np.array((1,2,3,4,5))
arr_t

array([1, 2, 3, 4, 5])

In [13]:
arr_t.dtype

dtype('int32')

If one number in the tuple is a float, the array type will be float

In [14]:
arr_t = np.array((1,2,3,4,5.4))
arr_t

array([1. , 2. , 3. , 4. , 5.4])

In [15]:
arr_t.dtype

dtype('float64')

Creating a 3x3 array with all zeros

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Creating a 3x3 array with all ones

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Creating a 3x3 array with all fives

In [18]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Creating a 3x3 array with random values between 0 and 1

In [19]:
np.random.random((3,3)) 

array([[0.78125916, 0.50720243, 0.87023946],
       [0.39756773, 0.80216213, 0.52498132],
       [0.73854951, 0.5962747 , 0.21989616]])

Creating a 3x3 array with integer random values between 0 and 10

In [20]:
np.random.random_integers(0,10,(3,3))

array([[ 9,  4,  9],
       [10,  8,  3],
       [10,  1,  1]])

Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1

In [21]:
np.random.normal(0,1,(3,3))

array([[-0.61350169, -0.11449687,  0.92101824],
       [ 0.62383692,  0.61498024, -0.40707322],
       [ 0.21479966, -0.81020984, -0.634365  ]])

Create a 3x3 array of normally distributed random values with mean 10 and standard deviation of 5

In [22]:
np.random.normal(10,5,(3,3))

array([[10.95399858, 11.26152857, -2.91303013],
       [10.20027402, 10.65320403, 10.82142911],
       [17.16400096, 13.49993229, 13.14694037]])

Create a 3x3 identity matrix

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a sequence of 11 values evenly spaced between 0 and 5 

In [24]:
l2 = np.linspace(0, 5, 11) 
print('Number of elements =',len(l2))
print(l2)

Number of elements = 11
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


Create a sequence of 6 values evenly spaced between 0 and 5 

In [25]:
np.linspace(0, 5, 6)

array([0., 1., 2., 3., 4., 5.])

Create a sequence of values between 0 and 20 (not included), stepping by 2

In [26]:
np.arange(0, 20, 2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

If you want to include 20, he second parameter must be 21:

In [27]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Create an array filled with a linear sequence between 0 and 21 (not included), stepping by 5

In [28]:
np.arange(0, 21, 5) 

array([ 0,  5, 10, 15, 20])

Create an array filled with a linear sequence between 0 and 28 (not included), stepping by 5

In [29]:
np.arange(0, 28, 5) 

array([ 0,  5, 10, 15, 20, 25])