# Array Operations

In [1]:
# For installing NumPy remove the # symbol and run the code in the following sentence
# !pip install numpy

In [2]:
import numpy as np

In [3]:
# Fixing seed for reproducibility
np.random.seed(0)     

## Creating NumPy arrays

In [4]:
# 1-D array
x1 = np.random.randint(10, size=8)        
x1

array([5, 0, 3, 3, 7, 9, 3, 5])

In [5]:
# 2-D array
x2 = np.random.randint(10, size=(2,4))    
x2

array([[2, 4, 7, 6],
       [8, 8, 1, 6]])

In [6]:
# 3-D array
x3 = np.random.randint(10, size=(2,2,2))  
x3

array([[[7, 7],
        [8, 1]],

       [[5, 9],
        [8, 9]]])

Let's start calculating dimensions, shape, and size:

In [7]:
print('Dim x1 =',x1.ndim)
print('Dim x2 =',x2.ndim)
print('Dim x3 =',x3.ndim)

Dim x1 = 1
Dim x2 = 2
Dim x3 = 3


In [8]:
print('Shape x1 =',x1.shape)
print('Shape x2 =',x2.shape)
print('Shape x3 =',x3.shape)

Shape x1 = (8,)
Shape x2 = (2, 4)
Shape x3 = (2, 2, 2)


In [9]:
print('Size x1 =',x1.size)
print('Size x2 =',x2.size)
print('Size x3 =',x3.size)

Size x1 = 8
Size x2 = 8
Size x3 = 8


## Accessing to array's elements

### 1-D array

In [10]:
print('x1 =',x1)    
print('First element:', x1[0])
print(' Last element:', x1[-1])

x1 = [5 0 3 3 7 9 3 5]
First element: 5
 Last element: 5


### 2-D array

In [11]:
print(x2)         
print('First element:', x2[0,0])
print('First element:', x2[0][0])
print('Last  element:', x2[-1,-1])
print('Last  element:', x2[-1][-1])

[[2 4 7 6]
 [8 8 1 6]]
First element: 2
First element: 2
Last  element: 6
Last  element: 6


### 3-D array

In [12]:
print(x3)            
print('First element:', x3[0,0,0])
print('First element:', x3[0][0][0])
print('Last  element:', x3[-1,-1,-1])
print('Last  element:', x3[-1][-1][-1])

[[[7 7]
  [8 1]]

 [[5 9]
  [8 9]]]
First element: 7
First element: 7
Last  element: 9
Last  element: 9


You can modify any value, if needed.

In [13]:
x3[-1,-1,-1] = 20
x3

array([[[ 7,  7],
        [ 8,  1]],

       [[ 5,  9],
        [ 8, 20]]])

`IMPORTANT`: NumPy arrays have a fixed type. If you attempt to insert a floating-point value to an integer array, the value will be silently truncated.

In [14]:
x3[-1,-1,-1] = 3.1415
x3

array([[[7, 7],
        [8, 1]],

       [[5, 9],
        [8, 3]]])

## Slicing

Slicing in python means taking elements from one given index to another given index.

We pass a slice instead of an index like this: `[start:end]`

We can also define the step like this: `[start:end:step]`

- **default value for start**: 0 
- **the default value for the end**: length of the array 
- **default value of step**: 1

In [15]:
x1

array([5, 0, 3, 3, 7, 9, 3, 5])

In [16]:
print('First three elements:',x1[:3])
print('Rest of the elements:',x1[3:])

First three elements: [5 0 3]
Rest of the elements: [3 7 9 3 5]


In [17]:
x = [0,1,2,3,4,5,6,7,8]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [18]:
print('First three elements:',x[:3])
print('Rest of the elements:',x[3:])

First three elements: [0, 1, 2]
Rest of the elements: [3, 4, 5, 6, 7, 8]


In [19]:
# index 2 is included, index 4 is excluded
x[2:4]

[2, 3]

In [20]:
print('Original array =', x, '\n')
print('From index 2 to 5, step 2:    ', x[2:5:2])
print('From index 2 to 5:            ', x[2:5])
print('From index 0 to 5, step 2:    ', x[:5:2])
print('From index 2 to last, step 2: ', x[2::2])

Original array = [0, 1, 2, 3, 4, 5, 6, 7, 8] 

From index 2 to 5, step 2:     [2, 4]
From index 2 to 5:             [2, 3, 4]
From index 0 to 5, step 2:     [0, 2, 4]
From index 2 to last, step 2:  [2, 4, 6, 8]


Reverse elements:

In [21]:
print('Original array =', x, '\n')
print('Reverse list:                            ',x[::-1])
print('Reverse list with step 2:                ',x[::-2])
print('Reverse list starting at index 4, step 2:',x[4::-2])

Original array = [0, 1, 2, 3, 4, 5, 6, 7, 8] 

Reverse list:                             [8, 7, 6, 5, 4, 3, 2, 1, 0]
Reverse list with step 2:                 [8, 6, 4, 2, 0]
Reverse list starting at index 4, step 2: [4, 2, 0]


In [22]:
m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
print('First column =', m[:,0])
print('First row    =', m[0,:])
print('First row    =', m[0])       

First column = [1 5 9]
First row    = [1 2 3 4]
First row    = [1 2 3 4]


In [24]:
# First two rows and first two columns
m[:2,:2]

array([[1, 2],
       [5, 6]])

In [25]:
# First two rows and first three columns
m[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [26]:
# First two rows and columns from 1 to 3-1=2
m[:2,1:3]

array([[2, 3],
       [6, 7]])

`IMPORTANT`: array slices in numpy return views rather than copies of the array data. 

This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

In [27]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
m_sub = m[:2,:2]
m_sub

array([[1, 2],
       [5, 6]])

In [29]:
m_sub[0,0] = 100
m_sub

array([[100,   2],
       [  5,   6]])

In [30]:
m

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets.

In [31]:
# Creating copies of arrays
m

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [32]:
m_sub_copy = m[:2,:2].copy()
m_sub_copy

array([[100,   2],
       [  5,   6]])

In [33]:
m_sub_copy[0,0] = 1
m_sub_copy

array([[1, 2],
       [5, 6]])

In [34]:
m

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

Reference:
- VanderPlas, J. (2017) Python Data Science Handbook: Essential Tools for Working with Data. USA: O’Reilly Media, Inc. chapter 2.