# NumPy array operations

In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
np.random.seed(0)   # seed for reproducibility

In [4]:
x1 = np.random.randint(10, size=8)        # one-dimensional array
x2 = np.random.randint(10, size=(2,4))    # two-dimensional array
x3 = np.random.randint(10, size=(2,2,2))  # three-dimensional array

Dimensions:

In [5]:
print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


Shape:

In [6]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(8,)
(2, 4)
(2, 2, 2)


Type:

In [7]:
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)

int32
int32
int32


Size:

In [8]:
print(x1.size)
print(x2.size)
print(x3.size)

8
8
8


Accesing elements:

In [9]:
print('x1 =',x1)
print('First element:', x1[0])
print('Last  element:', x1[-1])

x1 = [5 0 3 3 7 9 3 5]
First element: 5
Last  element: 5


In [10]:
print(x2)
print('First element:', x2[0,0])
print('First element:', x2[0][0])
print('Last  element:', x2[-1,-1])
print('Last  element:', x2[-1][-1])

[[2 4 7 6]
 [8 8 1 6]]
First element: 2
First element: 2
Last  element: 6
Last  element: 6


In [11]:
print(x3)
print('First element:', x3[0,0,0])
print('First element:', x3[0][0][0])
print('Last  element:', x3[-1,-1,-1])
print('Last  element:', x3[-1][-1][-1])

[[[7 7]
  [8 1]]

 [[5 9]
  [8 9]]]
First element: 7
First element: 7
Last  element: 9
Last  element: 9


You can modify any value, if needed.

In [12]:
x3[-1,-1,-1] = 20
x3

array([[[ 7,  7],
        [ 8,  1]],

       [[ 5,  9],
        [ 8, 20]]])

`IMPORTANT`: NumPy arrays have a fixed type. If you attempt to insert a floating-point value to an integer array, the value will be silently truncated.

In [13]:
x3[-1,-1,-1] = 3.1415
x3

array([[[7, 7],
        [8, 1]],

       [[5, 9],
        [8, 3]]])

## Accesing subarrays

In [14]:
print(x1)
print('First three elements:',x1[:3])
print('Rest of the elements:',x1[3:])

[5 0 3 3 7 9 3 5]
First three elements: [5 0 3]
Rest of the elements: [3 7 9 3 5]


In [15]:
x = [0,1,2,3,4,5,6,7,8]

In [16]:
# index 2 is included, index 4 is excluded
x[2:4]

[2, 3]

`x[start:stop:step]`
- default start: first index
- default stop: last index
- default step: 1

In [17]:
print('Original array =', x, '\n')
print('From index 2 to 5 with step 2      =', x[2:5:2])
print('From index 2 to 5, default step    =', x[2:5:])
print('From the first index to 5, step 2  =', x[:5:2])
print('From index 2 to last index, step 2 =', x[2::2])

Original array = [0, 1, 2, 3, 4, 5, 6, 7, 8] 

From index 2 to 5 with step 2      = [2, 4]
From index 2 to 5, default step    = [2, 3, 4]
From the first index to 5, step 2  = [0, 2, 4]
From index 2 to last index, step 2 = [2, 4, 6, 8]


Reverse elements:

In [18]:
print('Original array =', x, '\n')
print('Reverse list:',x[::-1])
print('Reverse list with step 2:',x[::-2])
print('Reverse list starting at index 4, with step 2:',x[4::-2])

Original array = [0, 1, 2, 3, 4, 5, 6, 7, 8] 

Reverse list: [8, 7, 6, 5, 4, 3, 2, 1, 0]
Reverse list with step 2: [8, 6, 4, 2, 0]
Reverse list starting at index 4, with step 2: [4, 2, 0]


In [19]:
m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
print('First column =', m[:,0])
print('First row    =', m[0,:])
print('First row    =', m[0])

First column = [1 5 9]
First row    = [1 2 3 4]
First row    = [1 2 3 4]


In [21]:
# First two rows and first two columns
m[:2,:2]

array([[1, 2],
       [5, 6]])

In [22]:
# First two rows and first three columns
m[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [23]:
# First two rows and columns from 1 to 3-1=2
m[:2,1:3]

array([[2, 3],
       [6, 7]])

`IMPORTANT`: array slices in numpy return views rather than copies of the array data. 

This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

In [24]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
m_sub = m[:2,:2]
m_sub

array([[1, 2],
       [5, 6]])

In [26]:
m_sub[0,0] = 100
m_sub

array([[100,   2],
       [  5,   6]])

In [27]:
m

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets.

In [28]:
# Creating copies of arrays
m

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [29]:
m_sub_copy = m[:2,:2].copy()
m_sub_copy

array([[100,   2],
       [  5,   6]])

In [30]:
m_sub_copy[0,0] = 1
m_sub_copy

array([[1, 2],
       [5, 6]])

In [31]:
m

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])