# Reshape array

`Reshaping of arrays`: The reshape() function is used to give a new shape to an array without changing its data. Array to be reshaped. The new shape should be compatible with the original shape.

In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
# Reshaping 3x4 array to 4x3 array 
m = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]]) 
print('Original array:\n', m)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
m2 = m.reshape(4, 3)
print('Reshaped array:\n',m2)

Reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
m3 = m.reshape(2,6)
m3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [6]:
# Remember the new shape must be compatible with the original shape.
m4 = m.reshape(2,5)         # This will raise an error

ValueError: cannot reshape array of size 12 into shape (2,5)

In [7]:
# Flatten array
m.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Introduction to universal functions

Computation on NumPy arrays can be very fast using vectorized operations implemented throught Numpy's universal functions.

In [8]:
# Operations on simple array
ar = np.arange(6)
ar

array([0, 1, 2, 3, 4, 5])

In [9]:
# Add 5 to every element
print(ar+5)

[ 5  6  7  8  9 10]


In [10]:
# Subtract 1 to every element
print(ar-1)

[-1  0  1  2  3  4]


In [11]:
# Multiply each element by 10
print(ar*10)

[ 0 10 20 30 40 50]


In [12]:
# Squaring each element of original array
print(ar**2)

[ 0  1  4  9 16 25]


In [13]:
# Double each element of original array
print(ar*2)

[ 0  2  4  6  8 10]


In [14]:
# Transpose the array
ar1 = np.array([[1,2,3],[4,5,6]])
print(ar1.T)

[[1 4]
 [2 5]
 [3 6]]


## Array concatenation

In [15]:
x0=np.zeros((2,2))
x0

array([[0., 0.],
       [0., 0.]])

In [16]:
x1=np.ones((2,2))
x1

array([[1., 1.],
       [1., 1.]])

In [17]:
concat1 = np.concatenate([x0,x1])
print(concat1,'\n')
print('Shape =',concat1.shape)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]] 

Shape = (4, 2)


In [18]:
concat2 = np.concatenate([x0,x1], axis=1)
print(concat2,'\n')
print('Shape =',concat2.shape)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]] 

Shape = (2, 4)


For working with arrays of mixed dimensions, it can be clearer to use:
- `np.vstack` (vertical stack) 
- `np.hstack` (horizontal stack) functions

In [19]:
# Using vstack
a1 = np.array([1,2,3])
print('a1 =\n',a1)
a2 = np.array([[4,4,4],[5,5,5]])
print('a2 =\n',a2)
np.vstack([a1,a2])

a1 =
 [1 2 3]
a2 =
 [[4 4 4]
 [5 5 5]]


array([[1, 2, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [20]:
# Using hstack
print('a2 =\n',a2)
a3 = np.array([[8],[8]])
print('a3 =\n',a3)
np.hstack([a2,a3])

a2 =
 [[4 4 4]
 [5 5 5]]
a3 =
 [[8]
 [8]]


array([[4, 4, 4, 8],
       [5, 5, 5, 8]])

## Array split

Splitting is the opposite of concatenation

In [21]:
x = np.arange(9)
print('x =',x)
x1, x2, x3 = np.split(x, 3)
print(x1)
print(x2)
print(x3)

x = [0 1 2 3 4 5 6 7 8]
[0 1 2]
[3 4 5]
[6 7 8]


You can decide where to cut the original array to get arrays with different sizes.

Here, we will get 3 arrays of different sizes:
- x1, from 0 to 2-1 (2 is not included)
- x2, from 2 to 6-1 (6 is not included)
- x3, from 6 to the latest element

In [22]:
x1, x2, x3 = np.split(x, [2,6])
print('x1 =', x1)
print('x2 =', x2)
print('x3 =', x3)

x1 = [0 1]
x2 = [2 3 4 5]
x3 = [6 7 8]


In [23]:
g = np.arange(16).reshape((4,4))
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
# vertical split
up, low = np.vsplit(g, 2)
print('up =\n',up)
print('low =\n',low)

up =
 [[0 1 2 3]
 [4 5 6 7]]
low =
 [[ 8  9 10 11]
 [12 13 14 15]]


In [25]:
# horizontal split
l, r = np.hsplit(g, 2)
print('left  =\n', l)
print('right =\n',r)

left  =
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right =
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
