## Reshape array

The reshape() function is used to give a new shape to an array without changing its data. Array to be reshaped. The new shape should be compatible with the original shape.

In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
m = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]]) 
print('Original array: shape =',m.shape, ' dim =', m.ndim)
m

Original array: shape = (3, 4)  dim = 2


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
m2 = m.reshape(4, 3)
print('shape =',m2.shape, ' dim =', m2.ndim)
m2

shape = (4, 3)  dim = 2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
m3 = m.reshape(2,6)
print('shape =',m3.shape, ' dim =', m3.ndim)
m3

shape = (2, 6)  dim = 2


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [6]:
m4 = m.reshape(1,12)
print('shape =',m4.shape, ' dim =', m4.ndim)
m4

shape = (1, 12)  dim = 2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [7]:
m5 = m.reshape(12,1)
print('shape =',m5.shape, ' dim =', m5.ndim)
m5

shape = (12, 1)  dim = 2


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

Remember the new shape must be compatible with the original shape.

In [8]:
m7 = m.reshape(2,5)         # This will raise an error

ValueError: cannot reshape array of size 12 into shape (2,5)

## Flatten array

In some cases, we need a one-dimensional array. That is, we need a copy of the array collapsed into one dimension.

In [9]:
m6 = m.reshape(12)
print('shape =',m6.shape, ' dim =', m6.ndim)
m6

shape = (12,)  dim = 1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

There is an easy way:

In [10]:
m7 = m.flatten()
print('shape =',m7.shape, ' dim =', m7.ndim)
m7

shape = (12,)  dim = 1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Iterating

Iterating means going through elements one by one.

In [11]:
# iterating 1-D array
for x in m6:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
# iterating 2-D array
for x in m3:
    print(x)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


If we iterate on a n-D array it will go through all dimensions one by one.

## Array concatenation

Concatenate a sequence of arrays

In [13]:
x0=np.zeros((2,2))
x0

array([[0., 0.],
       [0., 0.]])

In [14]:
x1=np.ones((2,2))
x1

array([[1., 1.],
       [1., 1.]])

In [15]:
concat1 = np.concatenate([x0,x1])
print(concat1,'\n')
print('Shape =',concat1.shape)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]] 

Shape = (4, 2)


In [16]:
concat2 = np.concatenate([x0,x1], axis=1)
print(concat2,'\n')
print('Shape =',concat2.shape)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]] 

Shape = (2, 4)


For working with arrays of mixed dimensions, it can be clearer to use:
- `np.vstack` (vertical stack) 
- `np.hstack` (horizontal stack) functions

In [17]:
# Using vstack
a1 = np.array([1,2,3])
print('a1 =\n',a1)
a2 = np.array([[4,4,4],[5,5,5]])
print('a2 =\n',a2)
np.vstack([a1,a2])

a1 =
 [1 2 3]
a2 =
 [[4 4 4]
 [5 5 5]]


array([[1, 2, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [18]:
# Using hstack
print('a2 =\n',a2)
a3 = np.array([[8],[8]])
print('a3 =\n',a3)
np.hstack([a2,a3])

a2 =
 [[4 4 4]
 [5 5 5]]
a3 =
 [[8]
 [8]]


array([[4, 4, 4, 8],
       [5, 5, 5, 8]])

## Array split

Splitting is the opposite of concatenation

In [19]:
x = np.arange(9)
print('x =',x)
x1, x2, x3 = np.split(x, 3)
print(x1)
print(x2)
print(x3)

x = [0 1 2 3 4 5 6 7 8]
[0 1 2]
[3 4 5]
[6 7 8]


You can decide where to cut the original array to get arrays with different sizes.

Here, we will get 3 arrays of different sizes:
- x1, from 0 to 2-1 (2 is not included)
- x2, from 2 to 6-1 (6 is not included)
- x3, from 6 to the latest element

In [20]:
x1, x2, x3 = np.split(x, [2,6])
print('x1 =', x1)
print('x2 =', x2)
print('x3 =', x3)

x1 = [0 1]
x2 = [2 3 4 5]
x3 = [6 7 8]


In [21]:
g = np.arange(16).reshape((4,4))
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
# vertical split
up, low = np.vsplit(g, 2)
print('up =\n',up)
print('low =\n',low)

up =
 [[0 1 2 3]
 [4 5 6 7]]
low =
 [[ 8  9 10 11]
 [12 13 14 15]]


In [23]:
# horizontal split
l, r = np.hsplit(g, 2)
print('left  =\n', l)
print('right =\n',r)

left  =
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right =
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Search

You can search an array for a certain value, and return the indexes that get a match.

In [24]:
ar = np.array([-5, 6, 4, 4, 1, 0, -6])
print('Searching for 1', np.where(ar == 1))

Searching for 1 (array([4], dtype=int64),)


In [25]:
print('Searching for 4', np.where(ar == 4))

Searching for 4 (array([2, 3], dtype=int64),)


In [26]:
print('Searching for 9', np.where(ar == 9))

Searching for 9 (array([], dtype=int64),)


In [27]:
# Find the index where the values are odd
# Remember % returns the remainder of the floor division
print('Searching for odd', np.where(ar%2 == 1))

Searching for odd (array([0, 4], dtype=int64),)


In [28]:
print('Searching for positive numbers', np.where(ar > 0))

Searching for positive numbers (array([1, 2, 3, 4], dtype=int64),)


## Sort

In [29]:
ar = np.random.randint(10, size=10)
print('Original array:',ar)
print('Sorted array:  ',np.sort(ar))

Original array: [0 9 6 2 6 2 7 3 6 6]
Sorted array:   [0 2 2 3 6 6 6 6 7 9]


This method returns a copy of the array, leaving the original array unchanged.

In [30]:
# Sorting a 2-D array
ar2 = np.array([[3, 2, 5], [7, 0, 1]])

print(np.sort(ar2))

[[2 3 5]
 [0 1 7]]


In [31]:
ar2 = np.array([[1,0,2],[5,6,4],[3,-1,6]])
ar2

array([[ 1,  0,  2],
       [ 5,  6,  4],
       [ 3, -1,  6]])

In [32]:
# array elements in sorted order by row
print(np.sort(ar2))

[[ 0  1  2]
 [ 4  5  6]
 [-1  3  6]]


In [33]:
# column-wise sorted array elements
print(np.sort(ar2, axis=0))

[[ 1 -1  2]
 [ 3  0  4]
 [ 5  6  6]]
