# Unary and Binary Operators in NumPy

## Unary Operators

In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# max: maximum element of array
print(arr.max())

6


In [5]:
# row-wise maximum element
print(arr.max(axis = 1))

[3 6]


In [6]:
# colums-wise maximum element
print(arr.max(axis = 0))

[4 5 6]


In [7]:
# min: minimum element of array
print(arr.min())

1


In [8]:
# sum: sum of array elements
print(arr.sum())

21


In [9]:
# row-wise sum of array elements
print(arr.sum(axis=1))

[ 6 15]


In [10]:
# cumulative sum along each row
print(arr.cumsum(axis=1))

[[ 1  3  6]
 [ 4  9 15]]


In [11]:
# cumulative sum along each column
print(arr.cumsum(axis=0))

[[1 2 3]
 [5 7 9]]


In [12]:
# cumulative sum
print(arr.cumsum())

[ 1  3  6 10 15 21]


## Binary Operators

In [13]:
ar1 = np.array([[0,1],[2,3]])
ar1

array([[0, 1],
       [2, 3]])

In [14]:
ar2 = np.array([[1,0],[0,1]])
ar2

array([[1, 0],
       [0, 1]])

In [15]:
ar3 = np.array([[1,1,1],[2,2,2]])
ar3

array([[1, 1, 1],
       [2, 2, 2]])

In [16]:
# sum
print(ar1 + ar2)

[[1 1]
 [2 4]]


For adding operation, the arrays must have the same shape

In [17]:
# subtraction
print(ar1 - ar2)

[[-1  1]
 [ 2  2]]


In [18]:
# multiply arrays (multiply element by element of arrays with the same shape)
print(ar1 * ar2)

[[0 0]
 [0 3]]


`matrix multiplication`: for matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix. The result is a matrix with the number of rowns of the first matrix and the number of columns of the second one.

In [19]:
print(ar1.dot(ar2))

[[0 1]
 [2 3]]


In [20]:
print('shape of ar1 =', ar1.shape)
print('shape of ar3 =', ar3.shape)
print(ar1.dot(ar3))

shape of ar1 = (2, 2)
shape of ar3 = (2, 3)
[[2 2 2]
 [8 8 8]]


## Introduction to universal functions

Computation on NumPy arrays can be very fast using vectorized operations implemented throught NumPy's universal functions (ufuncs).

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

| Operator | Equivalent ufunct | Description |
|---|---|---|
| + | np.add | Addition |
| - | np.subtract | Subtraction |
| - | np.negative | Unary negation |
| * | np.multiply | Multiplication |
| / | np.divide   | Division       |
| * | np.power    | Exponentiation |
| * | np.mod      | Modulus/remainder |

In [21]:
print('ar1 =\n',ar1)
print('ar2 =\n',ar2)
print('np.add =\n',np.add(ar1,ar2))

ar1 =
 [[0 1]
 [2 3]]
ar2 =
 [[1 0]
 [0 1]]
np.add =
 [[1 1]
 [2 4]]


In [22]:
print('np.subtract =\n',np.subtract(ar1,ar2))

np.subtract =
 [[-1  1]
 [ 2  2]]


In [23]:
print('np.multiply =\n',np.multiply(ar1,ar2))

np.multiply =
 [[0 0]
 [0 3]]


In [24]:
print('np.divide =\n',np.divide(ar1,ar2))

np.divide =
 [[ 0. inf]
 [inf  3.]]


To check if a function is a ufunc:

In [25]:
print(type(np.add))
print(type(np.subtract))
print(type(np.multiply))
print(type(np.divide))

<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


### Other ufuncts

In [26]:
x1 = [10, 20, 30, 40, 50]
x2 = [ 2,  3,  2,  3,  2]

In [27]:
# The power() function rises the values from the first array to the power of the values of the second array.
print('power =\n', np.power(x1,x2))

power =
 [  100  8000   900 64000  2500]


In [28]:
# The mod() function returns the remainder of the floor division of the values in the first array to the values in the second array.
print('mod =\n', np.mod(x1,x2))

mod =
 [0 2 0 1 0]


In [29]:
# You get the same result when using the remainder() function
print('remainder =\n', np.remainder(x1,x2))

remainder =
 [0 2 0 1 0]


In [30]:
# The absolute() function returns the absolute value operation element-wise.
x3 = [-5, 2, -3, -1, 6, 3]
print('absolute value =', np.absolute(x3))

absolute value = [5 2 3 1 6 3]


#### Trigonometric functions

In [31]:
ar = np.array([0, np.pi/2, np.pi])
ar

array([0.        , 1.57079633, 3.14159265])

In [32]:
# sin values
sin_ar = np.sin(ar)
print(sin_ar)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [33]:
# cos values
cos_ar = np.cos(ar)
print(cos_ar)

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [34]:
# trunc() truncate elements of array
print(np.trunc(sin_ar))
print(np.trunc(cos_ar))

[0. 1. 0.]
[ 1.  0. -1.]


#### Other operations

In [35]:
# Operations on simple array
ar = np.arange(6)
ar

array([0, 1, 2, 3, 4, 5])

In [36]:
# Add 5 to every element
print(ar+5)

[ 5  6  7  8  9 10]


In [37]:
# Subtract 1 to every element
print(ar-1)

[-1  0  1  2  3  4]


In [38]:
# Multiply each element by 10
print(ar*10)

[ 0 10 20 30 40 50]


In [39]:
# Squaring each element of original array
print(ar**2)

[ 0  1  4  9 16 25]


In [40]:
# Double each element of original array
print(ar*2)

[ 0  2  4  6  8 10]


In [41]:
# Transpose the array
ar1 = np.array([[1,2,3],[4,5,6]])
print(ar1.T)

[[1 4]
 [2 5]
 [3 6]]
