# Operators and Universal Functions

NumPy library is essential in the Data Science world because it provides a simple and versatile interface to optimize computation with data arrays.

In [1]:
import numpy as np

## Unary Operators

In [2]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

`max`: maximum element of array

In [3]:
print(arr.max())

6


row-wise maximum element

In [4]:
print(arr.max(axis = 1))

[3 6]


colums-wise maximum element

In [5]:
print(arr.max(axis = 0))

[4 5 6]


`min`: minimum element of array

In [6]:
print(arr.min())

1


`sum`: sum of array elements

In [7]:
print(arr.sum())

21


row-wise sum of array elements

In [8]:
print(arr.sum(axis=1))

[ 6 15]


cumulative sum along each row

In [9]:
print(arr.cumsum(axis=1))

[[ 1  3  6]
 [ 4  9 15]]


cumulative sum along each column

In [10]:
print(arr.cumsum(axis=0))

[[1 2 3]
 [5 7 9]]


`cumsum`: cumulative sum

In [11]:
print(arr.cumsum())

[ 1  3  6 10 15 21]


## Binary Operators

In [12]:
ar1 = np.array([[0,1],[2,3]])
ar1

array([[0, 1],
       [2, 3]])

In [13]:
ar2 = np.array([[1,1],[1,1]])
ar2

array([[1, 1],
       [1, 1]])

In [14]:
ar3 = np.array([[1,1,1],[2,2,2]])
ar3

array([[1, 1, 1],
       [2, 2, 2]])

**Sum**: for adding operation, the arrays must have the same shape

In [15]:
print(ar1 + ar2)

[[1 2]
 [3 4]]


**Subtraction**: For subtracting, the arrays must have the same shape

In [16]:
print(ar1 - ar2)

[[-1  0]
 [ 1  2]]


**Multiply arrays**: multiply element by element of arrays with the same shape

In [17]:
print(ar1 * ar2)

[[0 1]
 [2 3]]


**`matrix multiplication`**: for matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix. The result is a matrix with the number of rowns of the first matrix and the number of columns of the second one.

In [18]:
print(ar1.dot(ar2))

[[1 1]
 [5 5]]


In [19]:
print('shape of ar1 =', ar1.shape)
print('shape of ar3 =', ar3.shape)
print(ar1.dot(ar3))

shape of ar1 = (2, 2)
shape of ar3 = (2, 3)
[[2 2 2]
 [8 8 8]]


## Universal Functions

Computation on NumPy arrays can be very fast using vectorized operations implemented through NumPy's universal functions (ufuncs).

Converting iterative statements into a vector-based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

| Operator | Equivalent ufunct | Description |
|---|---|---|
| + | np.add | Addition |
| - | np.subtract | Subtraction |
| - | np.negative | Unary negation |
| * | np.multiply | Multiplication |
| / | np.divide   | Division       |
| ** | np.power    | Exponentiation |
| % | np.mod      | Modulus/remainder |

In [20]:
print('ar1 =\n',ar1)
print('ar2 =\n',ar2)
print('np.add =\n',np.add(ar1,ar2))

ar1 =
 [[0 1]
 [2 3]]
ar2 =
 [[1 1]
 [1 1]]
np.add =
 [[1 2]
 [3 4]]


In [21]:
print('np.subtract =\n',np.subtract(ar1,ar2))

np.subtract =
 [[-1  0]
 [ 1  2]]


In [22]:
print('np.multiply =\n',np.multiply(ar1,ar2))

np.multiply =
 [[0 1]
 [2 3]]


In [23]:
print('np.divide =\n',np.divide(ar1,ar2))

np.divide =
 [[0. 1.]
 [2. 3.]]


add, subtract, multiply and divide are ufunc

In [24]:
# Verifying that add, subtract, multiply and divide are ufunc
print(type(np.add))
print(type(np.subtract))
print(type(np.multiply))
print(type(np.divide))

<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


### Other ufuncts

In [25]:
x1 = [10, 20, 30, 40, 50]
x2 = [ 2,  3,  2,  3,  2]

The **power()** function rises the values from the first array to the power of the values of the second array.

In [26]:
print('power =', np.power(x1,x2))

power = [  100  8000   900 64000  2500]


The **mod()** function returns the remainder of the floor division of the values in the first array to the values in the second array.

In [27]:
print('mod =\n', np.mod(x1,x2))

mod =
 [0 2 0 1 0]


You get the same result when using the **remainder()** function.

In [28]:
print('remainder =\n', np.remainder(x1,x2))

remainder =
 [0 2 0 1 0]


The **absolute()** function returns the absolute value operation element-wise.

In [29]:
x3 = [-5, 2, -3, -1, 6, 3]
print('absolute value =', np.absolute(x3))

absolute value = [5 2 3 1 6 3]


NumPy broadcasting defines how it handles arrays of different shapes during arithmetic operations. The smaller array is "broadcast" across the bigger array, so that their shapes are consistent.

In [30]:
# Operations on simple array
ar = np.arange(6)

Remember scalers are arrays of dimension 0.

In [31]:
print('Original array:             ',ar)
print('Add 5 to each element:      ',ar+5)
print('Subtract 1 to each element: ',ar-1)
print('Multiply each element by 10:',ar*10)
print('Square of each element:     ',ar**2)

Original array:              [0 1 2 3 4 5]
Add 5 to each element:       [ 5  6  7  8  9 10]
Subtract 1 to each element:  [-1  0  1  2  3  4]
Multiply each element by 10: [ 0 10 20 30 40 50]
Square of each element:      [ 0  1  4  9 16 25]


Transpose the array

In [32]:
# Transpose the array
ar1 = np.array([[1,2,3],[4,5,6]])
print(ar1.T)

[[1 4]
 [2 5]
 [3 6]]


#### Trigonometric functions

In [33]:
x = np.array([0, np.pi/2, np.pi])

`sin` and `cos` values

In [34]:
# sin and cos values
print('sin:', np.sin(ar))
print('cos:', np.cos(ar))

sin: [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos: [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


`trunc` truncates the array elements

In [35]:
print('sin:', np.trunc(np.sin(ar)))
print('cos:', np.trunc(np.cos(ar)))

sin: [ 0.  0.  0.  0. -0. -0.]
cos: [ 1.  0. -0. -0. -0.  0.]


#### Logaritmic Functions

NumPy provides functions to perform log at the base 2 (`log2()`), e (`log()`) and 10 (`log10()`).

In [36]:
y = np.array([1, 2, 10, 100])

Getting the log at the base 2

In [37]:
print('log2 :', np.round(np.log2(y),2))
print('log  :', np.round(np.log(y),2))
print('log10:', np.round(np.log10(y),2))

log2 : [0.   1.   3.32 6.64]
log  : [0.   0.69 2.3  4.61]
log10: [0.  0.3 1.  2. ]


## References

- https://numpy.org/doc/stable/reference/ufuncs.html
- VanderPlas, J. (2017) Python Data Science Handbook: Essential Tools for Working with Data. USA: O’Reilly Media, Inc. chapter 2.