# Unary operators in numpy

In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# max: maximum element of array
print(arr.max())

6


In [5]:
# row-wise maximum element
print(arr.max(axis = 1))

[3 6]


In [6]:
# colums-wise maximum element
print(arr.max(axis = 0))

[4 5 6]


In [7]:
# min: minimum element of array
print(arr.min())

1


In [8]:
# sum: sum of array elements
print(arr.sum())

21


In [9]:
# row-wise sum of array elements
print(arr.sum(axis=1))

[ 6 15]


In [10]:
# cumulative sum along each row
print(arr.cumsum(axis=1))

[[ 1  3  6]
 [ 4  9 15]]


In [11]:
# cumulative sum along each column
print(arr.cumsum(axis=0))

[[1 2 3]
 [5 7 9]]


In [12]:
# cumulative sum
print(arr.cumsum())

[ 1  3  6 10 15 21]


## Binary operators in numpy

In [13]:
ar1 = np.array([[0,1],[2,3]])
ar1

array([[0, 1],
       [2, 3]])

In [14]:
ar2 = np.array([[1,0],[0,1]])
ar2

array([[1, 0],
       [0, 1]])

In [15]:
ar3 = np.array([[1,1,1],[2,2,2]])
ar3

array([[1, 1, 1],
       [2, 2, 2]])

In [16]:
# sum
print(ar1 + ar2)

[[1 1]
 [2 4]]


For adding operation, the arrays must have the same shape

In [17]:
# subtraction
print(ar1 - ar2)

[[-1  1]
 [ 2  2]]


For adding and subtraction operations, the arrays must have te same shape

In [18]:
print(ar1 + ar3)            # This will raise an error

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [19]:
# multiply arrays (multiply element by element of arrays with the same shape)
print(ar1 * ar2)

[[0 0]
 [0 3]]


`matrix multiplication`: for matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix. The result is a matrix with the number of rowns of the first matrix and the number of columns of the second one.

In [20]:
print(ar1.dot(ar2))

[[0 1]
 [2 3]]


In [21]:
print('shape of ar1 =', ar1.shape)
print('shape of ar3 =', ar3.shape)
print(ar1.dot(ar3))

shape of ar1 = (2, 2)
shape of ar3 = (2, 3)
[[2 2 2]
 [8 8 8]]


`Universal functions (ufunc)`: NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

In [22]:
ar = np.array([0, np.pi/2, np.pi])
ar

array([0.        , 1.57079633, 3.14159265])

In [23]:
# sin values
print(np.sin(ar))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [24]:
# cos values
print(np.cos(ar))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [25]:
# tan values
print(np.tan(ar))

[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [26]:
ar = np.arange(4)
ar

array([0, 1, 2, 3])

In [27]:
# exponential values
print(np.exp(ar))

[ 1.          2.71828183  7.3890561  20.08553692]


In [28]:
# square root of array values
print(np.sqrt(ar))

[0.         1.         1.41421356 1.73205081]


In [29]:
ar = np.array([1, -1, 3, -5])
ar

array([ 1, -1,  3, -5])

In [30]:
# Absolute value
print(abs(ar))

[1 1 3 5]


## Sorting an array in numpy

In [31]:
ar = np.array([[1,0,2],[5,6,4],[3,-1,6]])
ar

array([[ 1,  0,  2],
       [ 5,  6,  4],
       [ 3, -1,  6]])

In [32]:
# array elements in sorted order by row
print(np.sort(ar))

[[ 0  1  2]
 [ 4  5  6]
 [-1  3  6]]


In [33]:
# column-wise sorted array elements
print(np.sort(ar, axis=0))

[[ 1 -1  2]
 [ 3  0  4]
 [ 5  6  6]]
