# Fancy indexing

In [1]:
# !pip install numpy

In [2]:
import numpy as np

Fancy indexing means passing an array of indices to access multiple array elements at once. 

In [3]:
x = np.random.randint(100, size=10)
x

array([11, 57, 55, 35, 51, 74,  3, 49, 52, 64])

In [4]:
# Suppose we want to access four different values. We could do it like this:
[x[3], x[6], x[9], x[4]]

[35, 3, 64, 51]

In [5]:
# Using fancy indexing:
ind = [3, 6, 9, 4]
x[ind]

array([35,  3, 64, 51])

In [6]:
# Fancy indexing also work with multiple dimenssions
M = np.arange(12).reshape((3,4))
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
row = np.array([0,2,1])
col = np.array([2,1,3])
M[row, col]

array([2, 9, 7])

In [8]:
# Without fancy indexing
[M[0,2], M[2,1], M[1,3]]

[2, 9, 7]

In [9]:
# For even more powerful operations, fancy indexing can be combined with the other indexing schemes:
M[2, [2,0,1]]

array([10,  8,  9])

In [10]:
# Without fancy indexing
[M[2,2], M[2,0], M[2,1]]

[10, 8, 9]

In [11]:
M[1:, [2, 0 ,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [12]:
# Modifying values with fancy indexing
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
idx = np.array([0,3,7])
x[idx] = 100
x

array([100,   1,   2, 100,   4,   5,   6, 100,   8,   9])

In [14]:
# Changing the values of those index
x[idx] += 20
x

array([120,   1,   2, 120,   4,   5,   6, 120,   8,   9])

In [15]:
# Changing the values of those index
x[idx] -= 125
x

array([-5,  1,  2, -5,  4,  5,  6, -5,  8,  9])

### Numpy.unique

Find the unique elements of an array.
Returns the sorted unique elements of an array. 

There are three optional outputs in addition to the unique elements:
- the indices of the input array that give the unique values
- the indices of the unique array that reconstruct the input array
- the number of times each unique value comes up in the input array

In [16]:
arr = ['d','a','b','d','c','c','b', 'a','b','a']

In [17]:
np.unique(arr)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [18]:
# Using return_counts
unique, counts = np.unique(arr, return_counts=True)
print(dict(zip(unique, counts)))

{'a': 3, 'b': 3, 'c': 2, 'd': 2}


In [19]:
unique

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [20]:
counts

array([3, 3, 2, 2], dtype=int64)

In [21]:
# Using return_index: it returns the first index where each value appears
unique, idx = np.unique(arr, return_index=True)
print(dict(zip(unique, idx)))

{'a': 1, 'b': 2, 'c': 4, 'd': 0}


In [22]:
idx

array([1, 2, 4, 0], dtype=int64)

In [23]:
unique, inv = np.unique(arr, return_inverse=True)

In [24]:
inv

array([3, 0, 1, 3, 2, 2, 1, 0, 1, 0], dtype=int64)

In [25]:
#recovering the original array
unique[inv]

array(['d', 'a', 'b', 'd', 'c', 'c', 'b', 'a', 'b', 'a'], dtype='<U1')