# Fancy indexing

In [1]:
# For installing NumPy remove the # symbol and run the code in the following sentence
# !pip install numpy

In [2]:
import numpy as np

In [3]:
# Fixing seed for reproducibility
np.random.seed(0)  

Fancy indexing means passing an array of indices to access multiple array elements at once. 

In [4]:
x = np.random.randint(100, size=10)
x

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

Suppose we want to access four different values. We could do it like this:

In [5]:
[x[3], x[6], x[9], x[4]]

[67, 83, 87, 67]

Using fancy indexing:

In [6]:
# with fancy indexing
ind = [3, 6, 9, 4]
x[ind]

array([67, 83, 87, 67])

Fancy indexing also work with multiple dimenssions

In [7]:
M = np.arange(12).reshape((3,4))
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
row = np.array([0,2,1])
col = np.array([2,1,3])
M[row, col]

array([2, 9, 7])

In [9]:
# without fancy indexing
[M[0,2], M[2,1], M[1,3]]

[2, 9, 7]

For even more powerful operations, fancy indexing can be combined with the other indexing schemes:

In [10]:
M[2, [2,0,1]]

array([10,  8,  9])

In [11]:
# without fancy indexing
[M[2,2], M[2,0], M[2,1]]

[10, 8, 9]

In [12]:
# with fancy indexing
M[1:, [2, 0 ,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

Modifying values with fancy indexing

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
idx = np.array([0,3,7])
x[idx] = 100
x

array([100,   1,   2, 100,   4,   5,   6, 100,   8,   9])

Changing the values of those index

In [15]:
x[idx] += 20
x

array([120,   1,   2, 120,   4,   5,   6, 120,   8,   9])

In [16]:
x[idx] -= 125
x

array([-5,  1,  2, -5,  4,  5,  6, -5,  8,  9])

Create a filter array that will return only even elements from the original array:

In [17]:
filter1 = []
for elem in x:
    if elem %2 == 0:    # if elem is even
        filter1.append(True)
    else: 
        filter1.append(False)            
print(filter1)        

[False, False, True, False, True, False, True, False, True, False]


In [18]:
print(x[filter1])

[2 4 6 8]


Create a filter that returns only values greater than 5:

In [19]:
filter2 = x > 5
print(filter2)

[False False False False False False  True False  True  True]


In [20]:
print(x[filter2])

[6 8 9]


In [21]:
print(M)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
filter3 = M > 4
filter3

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
M[filter3]

array([ 5,  6,  7,  8,  9, 10, 11])

## NumPy unique

Find the unique elements of an array.

Returns the sorted unique elements of an array. 

There are three optional outputs in addition to the unique elements:
- the indices of the input array that give the unique values
- the indices of the unique array that reconstruct the input array
- the number of times each unique value comes up in the input array

In [24]:
arr = ['d','a','b','d','c','c','b', 'a','b','a']

In [25]:
np.unique(arr)

array(['a', 'b', 'c', 'd'], dtype='<U1')

Using return_counts:

In [26]:
unique, counts = np.unique(arr, return_counts=True)
print(dict(zip(unique, counts)))

{'a': 3, 'b': 3, 'c': 2, 'd': 2}


In [27]:
unique

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [28]:
counts

array([3, 3, 2, 2], dtype=int64)

Using return_index: it returns the first index where each value appears

In [29]:
unique, idx = np.unique(arr, return_index=True)
print(dict(zip(unique, idx)))

{'a': 1, 'b': 2, 'c': 4, 'd': 0}


In [30]:
idx

array([1, 2, 4, 0], dtype=int64)

In [31]:
unique, inv = np.unique(arr, return_inverse=True)

In [32]:
inv

array([3, 0, 1, 3, 2, 2, 1, 0, 1, 0], dtype=int64)

Recovering the original array:

In [33]:
unique[inv]

array(['d', 'a', 'b', 'd', 'c', 'c', 'b', 'a', 'b', 'a'], dtype='<U1')

Reference:
- VanderPlas, J. (2017) Python Data Science Handbook: Essential Tools for Working with Data. USA: O’Reilly Media, Inc. chapter 2.