# Boolean Arrays

In [1]:
# For installing NumPy remove the # symbol and run the code in the following sentence
# !pip install numpy

In [2]:
import numpy as np

In [3]:
# Fixing seed for reproducibility
np.random.seed(0)

## Comparison Operators

In [4]:
x = np.random.randint(-2, 5, size=6)
x

array([ 2,  3, -2,  1,  1,  1])

In [5]:
# less than 0
x < 0

array([False, False,  True, False, False, False])

In [6]:
# greater than 0
x > 0

array([ True,  True, False,  True,  True,  True])

In [7]:
# greater than or equal to 1
x >= 1

array([ True,  True, False,  True,  True,  True])

In [8]:
# not equal
x != 1

array([ True,  True,  True, False, False, False])

In [9]:
# equal
x == 2

array([ True, False, False, False, False, False])

**Working with 2 dimensional array**

In [10]:
x2 = np.random.randint(-2, 5, size=(3,4))
x2

array([[-1,  1,  3,  0],
       [ 2,  4, -2, -2],
       [ 2,  0, -1,  4]])

In [11]:
# less than or equal to 0
x2 <= 0

array([[ True, False, False,  True],
       [False, False,  True,  True],
       [False,  True,  True, False]])

In [12]:
# counting entries
np.count_nonzero(x2)

10

In [13]:
# counting negative values
np.count_nonzero(x2 < 0)

4

In [14]:
# counting positive values
np.count_nonzero(x2 > 0)

6

In [15]:
# counting positive values, another way
np.sum(x2 > 0)

6

In [16]:
# sum() can work along columns
np.sum(x2 > 0, axis=0)

array([2, 2, 1, 1])

In [17]:
# sum() can work along rows
np.sum(x2 > 0, axis=1)

array([2, 2, 2])

In [18]:
# Are there any value equal to 0?
np.any(x2 == 0)

True

In [19]:
# Columns with at least one 0
np.any(x2 == 0, axis=0)

array([False,  True, False,  True])

In [20]:
# Rows with at least one 0
np.any(x2 == 0, axis=1)

array([ True, False,  True])

In [21]:
# Are all values equal to 5?
np.all(x2 == 5)

False

## Boolean Arrays as Masks

In [22]:
# Getting the negative values
x2[x2 < 0]

array([-1, -2, -2, -1])

In [23]:
# Getting the positive values
x2[x2 > 0]

array([1, 3, 2, 4, 2, 4])

In [24]:
# Getting the values greater than 4
x2[x2 > 4]

array([], dtype=int32)

## Boolean Operators

| a | b | a `and` b | a `or` b |
|---|---|---------|---------|
|False|False|False|False|
|False|True|False|True|
|True|False|False|True|
|True|True|True|True|

| a | `not` a |
|---|---|
|False|True|
|True|False|

**Bitwise Boolean Operators**

| Operator | Equivalent ufunc |
|----------|------------------|
| **`&`** | np.bitwise_and |
| **`\|`** | np.bitwise_or |
| **`^`** | np.bitwise_xor |
| **`~`** | np.bitwise_not |

- `and` and `or` gauge the truth or falsehood of entire object
- `&` and `|` refer to bits within each object

In Python, all nonzero integers will evaluate as True. 

In [25]:
a = 9
b = 10

In [26]:
# True and True
a and b

10

The result is different from 0, which means it is True. Python only evaluates the right-side part of an "and" expression if the left part is truthy.

In [27]:
# True and True
b and a

9

The result is different from 0, which means it is True.

In [28]:
# Bitwise comparison
a & b

8

Let's convert `a` and `b` to binaries, and perform the bitwise `&` comparison.

In [29]:
# binary 
bin(9)

'0b1001'

In [30]:
# binary
bin(10)

'0b1010'

`1001 & 1010 = 1000`

Notice that the corresponding bits of the binary representation are compared in order to yield the result.

In [31]:
bin(8)

'0b1000'

When you have an array of Boolean values in NumPy, you can think of a string of bits where `1 = True` and `0 = False`, and the result of `&` and `|` operates similarly.

In [32]:
ar1 = np.random.randint(0, 2, size=10)
ar1

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1])

In [33]:
ar2 = np.random.randint(0, 2, size=10)
ar2

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [34]:
# Using the bitwise operator  
ar1 & ar2

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 0])

In [35]:
# Using the bitwise operator 
ar1 | ar2

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1])

In [36]:
ar1 and ar2         # This will raise an error

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [37]:
# Remember
x

array([ 2,  3, -2,  1,  1,  1])

In [38]:
# Getting the values between -1 and 1
x[(x >= -1) & (x <= 1)]

array([1, 1, 1])

In [39]:
# Remember
x2

array([[-1,  1,  3,  0],
       [ 2,  4, -2, -2],
       [ 2,  0, -1,  4]])

In [40]:
# Getting the values between -1 and 1
x2[(x2 >= -1) & (x2 <= 1)]

array([-1,  1,  0,  0, -1])

Reference:
- VanderPlas, J. (2017) Python Data Science Handbook: Essential Tools for Working with Data. USA: O’Reilly Media, Inc. chapter 2.